[package]
name = "libncrypt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde_bytes = "0.11.14"
